name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run ci-new
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: true
