name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "**.tsx"
      - "ava.config.js"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.ts"
      - "**.tsx"
      - "ava.config.js"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci.yml"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x, 20.x, 21.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm run ci

      - name: Codecov
        uses: codecov/codecov-action@v3
        if: matrix.node == '20.x' && matrix.os == 'ubuntu-latest'
        with:
          file: ./coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: false
