name: ESLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run eslint
