name: ESLint

on:
  push:
    branches: [master]
    paths:
      - useSuspender.js
      - "*.test.js"
      - .eslintrc.js
      - ".github/workflows/eslint.yml"

  pull_request:
    branches: [master]
    paths:
      - useSuspender.js
      - "*.test.js"
      - .eslintrc.js
      - ".github/workflows/eslint.yml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run eslint
