name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

job:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2

      - name: Setup Node.js
        uses: actions/setup-node@1
        with:
          node-version: 14

      - run: npm run eslint
