name: TypeScript Typings

on:
  push:
    branches: [master]
    paths:
      - useSuspender.d.ts
      - useSuspender.test-d.ts
      - ".github/workflows/types.yml"
  pull_request:
    branches: [master]
    paths:
      - useSuspender.d.ts
      - useSuspender.test-d.ts
      - ".github/workflows/types.yml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run test:types
